### ISSUE TITLE
Scrub is not displayed when running

### ISSUE THREAD

**Issue by hyperbart** [FireDrunk/ZFSmond#1]
Scrub status is not shown in interface.

**Comment by FireDrunk** [comment]
The information regarding the current scrub state of the pool has to come from libzfs-python.
I've contacted the developer of the library to check into the information, since it should be available in the ZFS core, but it's not (easily) published through the library.

So we have to wait until the upstream library gets updated.

**Comment by FireDrunk** [comment]
Library has been updated, and scrub information has been added.
